name: Checar codigo
on: [push, pull_request]

jobs:
  eslint:
    name: "Revisar eslint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Checar pull"
        if: github.event_name == 'push'
        uses: reviewdog/action-eslint@v1.16.1
        with:
          tool_name: "eslint check"
          reporter: github-check
          filter_mode: diff_context
          level: error

      - name: "Checar pull request"
        if: github.event_name == 'pull_request'
        uses: reviewdog/action-eslint@v1.16.1
        with:
          tool_name: "eslint pr review"
          reporter: github-pr-review
          filter_mode: added
          level: error
          fail_on_error: true
