name: Checar codigo
on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  eslint:
    name: "Executar eslint"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3

      - name: "Checar push"
        if: github.event_name == 'push'
        uses: reviewdog/action-eslint@v1.16.1
        with:
          tool_name: "eslint check"
          reporter: github-check
          filter_mode: added
          level: warning

      - name: "Checar pull request"
        if: |
          github.event_name == 'pull_request'
            && !contains(github.event.pull_request.labels.*.name, 'Ignorar verificação')

        uses: reviewdog/action-eslint@v1.16.1
        with:
          tool_name: "eslint pr review"
          reporter: github-pr-review
          filter_mode: added
          level: error
          fail_on_error: true
