name: Checar codigo
on: [pull_request]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Revisar diferencias"
        uses: reviewdog/action-eslint@v1.16.1
        with:
          tool_name: "eslint review"
          reporter: github-pr-review
          filter_mode: added
          level: error
          fail_on_error: true

      
      # - name: "Checar arquivos"
      #   uses: reviewdog/action-eslint@v1.16.1
      #   with:
      #     tool_name: "eslint check"
      #     reporter: github-pr-check
      #     level: error
      #     filter_mode: diff_context
          