name: Checar codigo
on: [pull_request]

jobs:
  eslint:
    name: eslint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: "Revisar diferencias"
        uses: reviewdog/action-eslint@v1.16.1
        with:
          reporter: github-pr-review
          filter_mode: diff_context
      - name: "Checar arquivos"
        uses: reviewdog/action-eslint@v1.16.1
        with:
          reporter: github-pr-check
          level: warning
          filter_mode: file
          