name: Testar comandos
on:   
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  testar:
    name: testar comandos
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '16'
      - name: Iniciar testes
        run: npm test true
